Django/project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('tasks/', include("tasks.urls", namespace='tasks')),
    path('quality_сontrol/', include("quality_control.urls", namespace='quality_control')),
]

Django/project_tracker/quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    # path('', views.index, name='quality_control'),
    path('', views.IndexView.as_view(), name='quality_control'),

    path('bugs/', views.bug_list, name='bug_list'),
    path('features/', views.feature_list, name='feature_list'),

    path('bugs/', views.BugsListView.as_view(), name='bug_list'),
    path('features/', views.FeaturesListView.as_view(), name='feature_list'),

    path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),
    path('features/<int:feature_id>/', views.feature_detail, name='feature_detail'),

    path('bugs/', views.BugsListView.as_view(), name='bug_list'),
    path('features/', views.FeaturesListView.as_view(), name='feature_list'),

    path('bugs/<int:bug_id>/', views.BugDetailView.as_view(), name='bug_detail'),
    path('features/<int:feature_id>/', views.FeatureDetailView.as_view(), name='feature_detail'),

    path('bugs/new/', views.add_bugreport, name='add_bugreport'),
    path('features/new/', views.add_feature, name='add_feature'),

    path('bugs/new/', views.BugCreateView.as_view(), name='add_bugreport'),
    path('features/new/', views.FeatureCreateView.as_view(), name='add_feature'),

    path('bugs/<int:bug_id>/update/', views.update_bug, name='update_bug'),
    path('features/<int:feature_id>/update/', views.update_feature, name='update_feature'),

    path('bugs/<int:bug_id>/delete/', views.delete_bug, name='delete_bug'),
    path('features/<int:feature_id>/delete/', views.delete_feature, name='delete_feature'),

    path('bugs/<int:bug_id>/delete/', views.BugDeleteView.as_view(), name='delete_bug'),
    path('features/<int:feature_id>/delete/', views.FeatureDeleteView.as_view(), name='delete_feature'),
]

Django/project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    # path('', views.index, name='tasks'),
    # path('another/', views.another_page, name='another_page'),
    path('', views.IndexView.as_view(), name='index'),

    path('projects/', views.projects_list, name='projects_list'),

    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),

    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),

    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),

    path('project/new/', views.create_project, name='add_new_project'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),

    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='create_task_in_project'),

    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.update_task, name='update_task'),

    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),

    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),

    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),

]

Django/project_tracker/quality_control/models.py
from django.db import models

from tasks.models import Project, Task


class BugReport(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True
    )
    STATUS_CHOICES = [
        ('New', 'Новый'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершено')
    ]
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='new'
    )
    PRIORITY_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
    ]
    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=1
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeatureRequest(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True
    )
    STATUS_CHOICES = [
        ('Consideration', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Rejected', 'Отклонено')
    ]
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='Consideration'
    )
    PRIORITY_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
    ]
    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=1
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/project_tracker/quality_control/forms.py
from django import forms
from django.forms import ModelForm
from .models import BugReport, FeatureRequest


class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

Django/project_tracker/quality_control/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import BugReport, FeatureRequest
from django.views.generic import CreateView, ListView, DeleteView
from django.urls import reverse, reverse_lazy
from .forms import BugReportForm, FeatureRequestForm
from django.shortcuts import redirect
from django.views import View
from django.views.generic import DetailView, UpdateView

# def index(request):
#     #another_page_url = reverse('quality_control:another_page')
#     bugs_page_url = reverse('quality_control:bug_list')
#     features_page_url = reverse('quality_control:feature_list')
#     html = f"<h1>Система контроля качества</h1><a href='{bugs_page_url}'>Список всех багов<br /></a><a href='{features_page_url}'>Запросы на улучшение</a>"
#     return HttpResponse(html)

##########################################################################################
def index(request):
    return render(request, 'quality_control/index.html')
# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         bugs_page_url = reverse('quality_control:bug_list')
#         features_page_url = reverse('quality_control:feature_list')
#         html = f"<h1>Система контроля качества</h1><a href='{bugs_page_url}'>Список всех багов<br /></a><a href='{features_page_url}'>Запросы на улучшение</a>"
#         return HttpResponse(html)

class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')

##########################################################################################

def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bug_list':bugs})

# def bug_list(request):
#     bugs = BugReport.objects.all()
#
#     bugs_html = "<h1>Cписок отчетов об ошибках</h1>"
#     for bug in bugs:
#         bugs_html += (f'<h3>{bug.title}</h3>Статус: {bug.status}<br /><a href="{bug.id}/">Подробнее</a>')
#     bugs_html += "</ul>"
#     return HttpResponse(bugs_html)

def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'feature_list':features})

# def feature_list(request):
#     features = FeatureRequest.objects.all()
#
#     features_html = "<h1>Список запросов на улучшение</h1>"
#     for feature in features:
#         features_html += (f'<h3>{feature.title}</h3>Статус: {feature.status}<br /><a href="{feature.id}/">Подробнее</a>')
#
#     features_html += "</ul>"
#     return HttpResponse(features_html)

class BugsListView(ListView):
    model = BugReport # модель работает с представлением объектов BugReport
    template_name = 'quality_control/bug_list.html'

class FeaturesListView(ListView):
    model = FeatureRequest # модель работает с представлением объектов FeatureRequest
    template_name = 'quality_control/feature_list.html'

##########################################################################################

def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bugreport':bug})

def feature_detail(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'featurerequest':feature})

class BugDetailView(DetailView):
    model = BugReport # модель работает с представлением объектов BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_detail.html'

# class BugDetailView(DetailView):
#     model = BugReport # модель работает с представлением объектов BugReport
#     pk_url_kwarg = 'bug_id'
#     def get(self, request, *args, **kwargs):
#
#         bug = self.get_object()
#
#         response_html = f'<h1>{bug.title}</h1><li><b>Описание:</b> {bug.description}</li>' +\
#                         f'<li><b>Статус:</b> {bug.status}</li><li><b>Приоритет:</b> {bug.priority}</li>' +\
#                         f'<li><b>Проект:</b> {bug.project}</li><li><b>Задача:</b> {bug.task}</li>'
#         return HttpResponse(response_html)

# class FeatureDetailView(DetailView):
#     model = FeatureRequest # модель работает с представлением объектов FeatureRequest
#     pk_url_kwarg = 'feature_id'
#     def get(self, request, *args, **kwargs):
#
#         feature = self.get_object()
#
#         response_html = f'<h1>{feature.title}</h1><li><b>Описание:</b> {feature.description}</li>' +\
#                         f'<li><b>Статус:</b> {feature.status}</li><li><b>Приоритет:</b> {feature.priority}</li>' +\
#                         f'<li><b>Проект:</b> {feature.project}</li><li><b>Задача:</b> {feature.task}</li>'
#         return HttpResponse(response_html)

class FeatureDetailView(DetailView):
    model = FeatureRequest # модель работает с представлением объектов FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_detail.html'


#############################################################################################
def add_bugreport(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_list')
    else:
        form = BugReportForm()

    return render(request, 'quality_control/bug_report_form.html', {'form': form})

def add_feature(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_list')
    else:
        form = FeatureRequestForm()

    return render(request, 'quality_control/feature_request_form.html', {'form': form})

class BugCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'
    success_url = reverse_lazy('quality_control:add_bugreport')

class FeatureCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'
    def form_valid(self, form):
        form.instanse.project = get_object_or_404(FeatureRequest, pk=self.kwargs['feature_id'])
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('quality_control:feature_detail', kwargs={'feature_id': self.kwargs['feature_id']})

#############################################################################################

def update_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id=bug.id)
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_update.html', {'form': form, 'bug':bug})

def update_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_detail', feature_id=feature_id)
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_update.html', {'form': form, 'feature':feature})

class BugUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')

class FeatureUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_update.html'
    pk_url_kwarg = 'feature_id'
    def get_success_url(self):
        return reverse('quality_control:feature_detail', kwargs={'feature_id': self.object.feature.id})


#############################################################################################


def delete_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bug_list')

def delete_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:feature_list')


class BugDeleteView(DeleteView):
    model = BugReport
    template_name = 'quality_control/bug_confirm_delete.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')

class FeatureDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    def get_success_url(self):
        return reverse('quality_control:feature_detail', kwargs={'feature_id': self.object.feature.id})

#############################################################################################

Django/project_tracker/quality_control/templates/quality_control/bug_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Удаление отчета об ошибке {{ bug.name }}</h2>
    <h3>Вы уверены, что хотите удалить отчет об ошибке "{{ bug.name }}"?</h3>

    <form action="{% url 'quality_control:delete_bug' bug.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail' bug.id %}">Отмена</a>
    </form>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h3>{{bugreport.title}}</h3>

    <p><a href="{% url 'quality_control:update_bug' bugreport.id %}">Изменить отчет</a></p>

    <p><a href="{% url 'quality_control:delete_bug' bugreport.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот отчет об ошибке?');">Удалить отчет</a></p>

    <ul>
        <li><b>Описание:</b> {{bugreport.description}}</li>
        <li><b>Статус:</b> {{bugreport.status}}</li>
        <li><b>Приоритет:</b> {{bugreport.priority}}</li>
        <li><b>Проект:</b> {{bugreport.project}}</li>
        <li><b>Задача:</b> {{bugreport.task}}</li>
    </ul>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Cписок отчетов об ошибках</h2>

    <p><a href="{% url 'quality_control:add_bugreport' %}">Создать новый отчет об ошибке</a></p>

    <ul>
        {% for bug in bug_list %}
            <h3>{{bug.title}}</h3>
            <a>Статус: {{bug.status}}<br /></a>
            <a href="{% url 'quality_control:bug_detail' bug.id %}">Подробнее</a>
        {% endfor %}
    </ul>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Создать новый отчет об ошибке</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Сохранить</button>
        </form>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/bug_update.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Изменение отчета об ошибке {{ bug.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Удаление улучшения {{ feature.name }}</h2>
    <h3>Вы уверены, что хотите удалить улучшение "{{ feature.name }}"?</h3>

    <form action="{% url 'quality_control:delete_feature' feature.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_detail' feature.id %}">Отмена</a>
    </form>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h3>{{featurerequest.title}}</h3>

    <p><a href="{% url 'quality_control:update_feature' featurerequest.id %}">Изменить предложение об улучшении</a></p>

    <p><a href="{% url 'quality_control:delete_feature' featurerequest.id %}"onclick="return confirm('Вы уверены, что хотите удалить это улучшение?');">Удалить улучшение</a></p>


    <ul>
        <li><b>Описание:</b> {{featurerequest.description}}</li>
        <li><b>Статус:</b> {{featurerequest.status}}</li>
        <li><b>Приоритет:</b> {{featurerequest.priority}}</li>
        <li><b>Проект:</b> {{featurerequest.project}}</li>
        <li><b>Задача:</b> {{featurerequest.task}}</li>
    </ul>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Список запросов на улучшение</h2>

    <p><a href="{% url 'quality_control:add_feature' %}">Предложить улучшение</a></p>

    <ul>
        {% for feature in feature_list %}
            <h3>{{ feature.title }}</h3>
            <a>Статус: {{ feature.status }}<br /></a>
            <a href="{% url 'quality_control:feature_detail' feature.id %}">Подробнее</a>
        {% endfor %}
    </ul>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Предложить улучшение</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Предложить</button>
        </form>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/feature_update.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Изменение предложения об улучшении {{ feature.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

Django/project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Система контроля качества</h1>
    <a href="{% url 'quality_control:bug_list' %}">Список всех багов<br /></a>
    <a href="{% url 'quality_control:feature_list' %}">Запросы на улучшение</a>

{% endblock %}